---
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"

kibana:
  image: mikew/kibana4
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  environment:
    ES_URL: "http://elasticsearch:9200/"

logstash:
  image: logstash
  links:
    - elasticsearch
  command: "logstash -e \"input { file { path => '/var/log/messages' } } output { elasticsearch { host=> 'elasticsearch' port=> '9200' protocol=> 'http' } }\""
